// ============ 180 COUNTRIES WITH FLAGS, CURRENCIES, SYMBOLS ============
const COUNTRIES = [
    { code: "AF", name: "Afghanistan", currency: "AFN", flag: "🇦🇫", symbol: "؋" },
    { code: "AL", name: "Albania", currency: "ALL", flag: "🇦🇱", symbol: "L" },
    { code: "DZ", name: "Algeria", currency: "DZD", flag: "🇩🇿", symbol: "د.ج" },
    { code: "AO", name: "Angola", currency: "AOA", flag: "🇦🇴", symbol: "Kz" },
    { code: "AR", name: "Argentina", currency: "ARS", flag: "🇦🇷", symbol: "$" },
    { code: "AM", name: "Armenia", currency: "AMD", flag: "🇦🇲", symbol: "֏" },
    { code: "AU", name: "Australia", currency: "AUD", flag: "🇦🇺", symbol: "$" },
    { code: "AT", name: "Austria", currency: "EUR", flag: "🇦🇹", symbol: "€" },
    { code: "AZ", name: "Azerbaijan", currency: "AZN", flag: "🇦🇿", symbol: "₼" },
    { code: "BS", name: "Bahamas", currency: "BSD", flag: "🇧🇸", symbol: "$" },
    { code: "BH", name: "Bahrain", currency: "BHD", flag: "🇧🇭", symbol: ".د.ب" },
    { code: "BD", name: "Bangladesh", currency: "BDT", flag: "🇧🇩", symbol: "৳" },
    { code: "BB", name: "Barbados", currency: "BBD", flag: "🇧🇧", symbol: "$" },
    { code: "BY", name: "Belarus", currency: "BYN", flag: "🇧🇾", symbol: "Br" },
    { code: "BE", name: "Belgium", currency: "EUR", flag: "🇧🇪", symbol: "€" },
    { code: "BZ", name: "Belize", currency: "BZD", flag: "🇧🇿", symbol: "$" },
    { code: "BJ", name: "Benin", currency: "XOF", flag: "🇧🇯", symbol: "Fr" },
    { code: "BT", name: "Bhutan", currency: "BTN", flag: "🇧🇹", symbol: "Nu." },
    { code: "BO", name: "Bolivia", currency: "BOB", flag: "🇧🇴", symbol: "Bs." },
    { code: "BA", name: "Bosnia", currency: "BAM", flag: "🇧🇦", symbol: "KM" },
    { code: "BW", name: "Botswana", currency: "BWP", flag: "🇧🇼", symbol: "P" },
    { code: "BR", name: "Brazil", currency: "BRL", flag: "🇧🇷", symbol: "R$" },
    { code: "BN", name: "Brunei", currency: "BND", flag: "🇧🇳", symbol: "$" },
    { code: "BG", name: "Bulgaria", currency: "BGN", flag: "🇧🇬", symbol: "лв" },
    { code: "BF", name: "Burkina Faso", currency: "XOF", flag: "🇧🇫", symbol: "Fr" },
    { code: "BI", name: "Burundi", currency: "BIF", flag: "🇧🇮", symbol: "Fr" },
    { code: "CV", name: "Cabo Verde", currency: "CVE", flag: "🇨🇻", symbol: "$" },
    { code: "KH", name: "Cambodia", currency: "KHR", flag: "🇰🇭", symbol: "៛" },
    { code: "CM", name: "Cameroon", currency: "XAF", flag: "🇨🇲", symbol: "Fr" },
    { code: "CA", name: "Canada", currency: "CAD", flag: "🇨🇦", symbol: "$" },
    { code: "CF", name: "Central African Republic", currency: "XAF", flag: "🇨🇫", symbol: "Fr" },
    { code: "TD", name: "Chad", currency: "XAF", flag: "🇹🇩", symbol: "Fr" },
    { code: "CL", name: "Chile", currency: "CLP", flag: "🇨🇱", symbol: "$" },
    { code: "CN", name: "China", currency: "CNY", flag: "🇨🇳", symbol: "¥" },
    { code: "CO", name: "Colombia", currency: "COP", flag: "🇨🇴", symbol: "$" },
    { code: "KM", name: "Comoros", currency: "KMF", flag: "🇰🇲", symbol: "Fr" },
    { code: "CG", name: "Congo", currency: "XAF", flag: "🇨🇬", symbol: "Fr" },
    { code: "CR", name: "Costa Rica", currency: "CRC", flag: "🇨🇷", symbol: "₡" },
    { code: "CI", name: "Côte d'Ivoire", currency: "XOF", flag: "🇨🇮", symbol: "Fr" },
    { code: "HR", name: "Croatia", currency: "EUR", flag: "🇭🇷", symbol: "€" },
    { code: "CU", name: "Cuba", currency: "CUP", flag: "🇨🇺", symbol: "$" },
    { code: "CY", name: "Cyprus", currency: "EUR", flag: "🇨🇾", symbol: "€" },
    { code: "CZ", name: "Czech Republic", currency: "CZK", flag: "🇨🇿", symbol: "Kč" },
    { code: "DK", name: "Denmark", currency: "DKK", flag: "🇩🇰", symbol: "kr" },
    { code: "DJ", name: "Djibouti", currency: "DJF", flag: "🇩🇯", symbol: "Fr" },
    { code: "DO", name: "Dominican Republic", currency: "DOP", flag: "🇩🇴", symbol: "$" },
    { code: "EC", name: "Ecuador", currency: "USD", flag: "🇪🇨", symbol: "$" },
    { code: "EG", name: "Egypt", currency: "EGP", flag: "🇪🇬", symbol: "£" },
    { code: "SV", name: "El Salvador", currency: "USD", flag: "🇸🇻", symbol: "$" },
    { code: "GQ", name: "Equatorial Guinea", currency: "XAF", flag: "🇬🇶", symbol: "Fr" },
    { code: "ER", name: "Eritrea", currency: "ERN", flag: "🇪🇷", symbol: "Nfk" },
    { code: "EE", name: "Estonia", currency: "EUR", flag: "🇪🇪", symbol: "€" },
    { code: "SZ", name: "Eswatini", currency: "SZL", flag: "🇸🇿", symbol: "L" },
    { code: "ET", name: "Ethiopia", currency: "ETB", flag: "🇪🇹", symbol: "Br" },
    { code: "FJ", name: "Fiji", currency: "FJD", flag: "🇫🇯", symbol: "$" },
    { code: "FI", name: "Finland", currency: "EUR", flag: "🇫🇮", symbol: "€" },
    { code: "FR", name: "France", currency: "EUR", flag: "🇫🇷", symbol: "€" },
    { code: "GA", name: "Gabon", currency: "XAF", flag: "🇬🇦", symbol: "Fr" },
    { code: "GM", name: "Gambia", currency: "GMD", flag: "🇬🇲", symbol: "D" },
    { code: "GE", name: "Georgia", currency: "GEL", flag: "🇬🇪", symbol: "₾" },
    { code: "DE", name: "Germany", currency: "EUR", flag: "🇩🇪", symbol: "€" },
    { code: "GH", name: "Ghana", currency: "GHS", flag: "🇬🇭", symbol: "₵" },
    { code: "GR", name: "Greece", currency: "EUR", flag: "🇬🇷", symbol: "€" },
    { code: "GT", name: "Guatemala", currency: "GTQ", flag: "🇬🇹", symbol: "Q" },
    { code: "GN", name: "Guinea", currency: "GNF", flag: "🇬🇳", symbol: "Fr" },
    { code: "GW", name: "Guinea-Bissau", currency: "XOF", flag: "🇬🇼", symbol: "Fr" },
    { code: "GY", name: "Guyana", currency: "GYD", flag: "🇬🇾", symbol: "$" },
    { code: "HT", name: "Haiti", currency: "HTG", flag: "🇭🇹", symbol: "G" },
    { code: "HN", name: "Honduras", currency: "HNL", flag: "🇭🇳", symbol: "L" },
    { code: "HU", name: "Hungary", currency: "HUF", flag: "🇭🇺", symbol: "Ft" },
    { code: "IS", name: "Iceland", currency: "ISK", flag: "🇮🇸", symbol: "kr" },
    { code: "IN", name: "India", currency: "INR", flag: "🇮🇳", symbol: "₹" },
    { code: "ID", name: "Indonesia", currency: "IDR", flag: "🇮🇩", symbol: "Rp" },
    { code: "IR", name: "Iran", currency: "IRR", flag: "🇮🇷", symbol: "﷼" },
    { code: "IQ", name: "Iraq", currency: "IQD", flag: "🇮🇶", symbol: "ع.د" },
    { code: "IE", name: "Ireland", currency: "EUR", flag: "🇮🇪", symbol: "€" },
    { code: "IL", name: "Israel", currency: "ILS", flag: "🇮🇱", symbol: "₪" },
    { code: "IT", name: "Italy", currency: "EUR", flag: "🇮🇹", symbol: "€" },
    { code: "JM", name: "Jamaica", currency: "JMD", flag: "🇯🇲", symbol: "$" },
    { code: "JP", name: "Japan", currency: "JPY", flag: "🇯🇵", symbol: "¥" },
    { code: "JO", name: "Jordan", currency: "JOD", flag: "🇯🇴", symbol: "د.ا" },
    { code: "KZ", name: "Kazakhstan", currency: "KZT", flag: "🇰🇿", symbol: "₸" },
    { code: "KE", name: "Kenya", currency: "KES", flag: "🇰🇪", symbol: "KSh" },
    { code: "KW", name: "Kuwait", currency: "KWD", flag: "🇰🇼", symbol: "د.ك" },
    { code: "KG", name: "Kyrgyzstan", currency: "KGS", flag: "🇰🇬", symbol: "с" },
    { code: "LA", name: "Laos", currency: "LAK", flag: "🇱🇦", symbol: "₭" },
    { code: "LV", name: "Latvia", currency: "EUR", flag: "🇱🇻", symbol: "€" },
    { code: "LB", name: "Lebanon", currency: "LBP", flag: "🇱🇧", symbol: "ل.ل" },
    { code: "LS", name: "Lesotho", currency: "LSL", flag: "🇱🇸", symbol: "L" },
    { code: "LR", name: "Liberia", currency: "LRD", flag: "🇱🇷", symbol: "$" },
    { code: "LY", name: "Libya", currency: "LYD", flag: "🇱🇾", symbol: "ل.د" },
    { code: "LT", name: "Lithuania", currency: "EUR", flag: "🇱🇹", symbol: "€" },
    { code: "LU", name: "Luxembourg", currency: "EUR", flag: "🇱🇺", symbol: "€" },
    { code: "MG", name: "Madagascar", currency: "MGA", flag: "🇲🇬", symbol: "Ar" },
    { code: "MW", name: "Malawi", currency: "MWK", flag: "🇲🇼", symbol: "MK" },
    { code: "MY", name: "Malaysia", currency: "MYR", flag: "🇲🇾", symbol: "RM" },
    { code: "MV", name: "Maldives", currency: "MVR", flag: "🇲🇻", symbol: ".ރ" },
    { code: "ML", name: "Mali", currency: "XOF", flag: "🇲🇱", symbol: "Fr" },
    { code: "MT", name: "Malta", currency: "EUR", flag: "🇲🇹", symbol: "€" },
    { code: "MR", name: "Mauritania", currency: "MRU", flag: "🇲🇷", symbol: "UM" },
    { code: "MU", name: "Mauritius", currency: "MUR", flag: "🇲🇺", symbol: "₨" },
    { code: "MX", name: "Mexico", currency: "MXN", flag: "🇲🇽", symbol: "$" },
    { code: "MD", name: "Moldova", currency: "MDL", flag: "🇲🇩", symbol: "L" },
    { code: "MN", name: "Mongolia", currency: "MNT", flag: "🇲🇳", symbol: "₮" },
    { code: "MA", name: "Morocco", currency: "MAD", flag: "🇲🇦", symbol: "د.م." },
    { code: "MZ", name: "Mozambique", currency: "MZN", flag: "🇲🇿", symbol: "MT" },
    { code: "MM", name: "Myanmar", currency: "MMK", flag: "🇲🇲", symbol: "Ks" },
    { code: "NA", name: "Namibia", currency: "NAD", flag: "🇳🇦", symbol: "$" },
    { code: "NP", name: "Nepal", currency: "NPR", flag: "🇳🇵", symbol: "₨" },
    { code: "NL", name: "Netherlands", currency: "EUR", flag: "🇳🇱", symbol: "€" },
    { code: "NZ", name: "New Zealand", currency: "NZD", flag: "🇳🇿", symbol: "$" },
    { code: "NI", name: "Nicaragua", currency: "NIO", flag: "🇳🇮", symbol: "C$" },
    { code: "NE", name: "Niger", currency: "XOF", flag: "🇳🇪", symbol: "Fr" },
    { code: "NG", name: "Nigeria", currency: "NGN", flag: "🇳🇬", symbol: "₦" },
    { code: "NO", name: "Norway", currency: "NOK", flag: "🇳🇴", symbol: "kr" },
    { code: "OM", name: "Oman", currency: "OMR", flag: "🇴🇲", symbol: "ر.ع." },
    { code: "PK", name: "Pakistan", currency: "PKR", flag: "🇵🇰", symbol: "₨" },
    { code: "PA", name: "Panama", currency: "PAB", flag: "🇵🇦", symbol: "B/." },
    { code: "PG", name: "Papua New Guinea", currency: "PGK", flag: "🇵🇬", symbol: "K" },
    { code: "PY", name: "Paraguay", currency: "PYG", flag: "🇵🇾", symbol: "₲" },
    { code: "PE", name: "Peru", currency: "PEN", flag: "🇵🇪", symbol: "S/" },
    { code: "PH", name: "Philippines", currency: "PHP", flag: "🇵🇭", symbol: "₱" },
    { code: "PL", name: "Poland", currency: "PLN", flag: "🇵🇱", symbol: "zł" },
    { code: "PT", name: "Portugal", currency: "EUR", flag: "🇵🇹", symbol: "€" },
    { code: "QA", name: "Qatar", currency: "QAR", flag: "🇶🇦", symbol: "ر.ق" },
    { code: "RO", name: "Romania", currency: "RON", flag: "🇷🇴", symbol: "lei" },
    { code: "RU", name: "Russia", currency: "RUB", flag: "🇷🇺", symbol: "₽" },
    { code: "RW", name: "Rwanda", currency: "RWF", flag: "🇷🇼", symbol: "Fr" },
    { code: "SA", name: "Saudi Arabia", currency: "SAR", flag: "🇸🇦", symbol: "ر.س" },
    { code: "SN", name: "Senegal", currency: "XOF", flag: "🇸🇳", symbol: "Fr" },
    { code: "RS", name: "Serbia", currency: "RSD", flag: "🇷🇸", symbol: "дин" },
    { code: "SC", name: "Seychelles", currency: "SCR", flag: "🇸🇨", symbol: "₨" },
    { code: "SL", name: "Sierra Leone", currency: "SLL", flag: "🇸🇱", symbol: "Le" },
    { code: "SG", name: "Singapore", currency: "SGD", flag: "🇸🇬", symbol: "$" },
    { code: "SK", name: "Slovakia", currency: "EUR", flag: "🇸🇰", symbol: "€" },
    { code: "SI", name: "Slovenia", currency: "EUR", flag: "🇸🇮", symbol: "€" },
    { code: "SO", name: "Somalia", currency: "SOS", flag: "🇸🇴", symbol: "Sh" },
    { code: "ZA", name: "South Africa", currency: "ZAR", flag: "🇿🇦", symbol: "R" },
    { code: "KR", name: "South Korea", currency: "KRW", flag: "🇰🇷", symbol: "₩" },
    { code: "SS", name: "South Sudan", currency: "SSP", flag: "🇸🇸", symbol: "£" },
    { code: "ES", name: "Spain", currency: "EUR", flag: "🇪🇸", symbol: "€" },
    { code: "LK", name: "Sri Lanka", currency: "LKR", flag: "🇱🇰", symbol: "₨" },
    { code: "SD", name: "Sudan", currency: "SDG", flag: "🇸🇩", symbol: "ج.س." },
    { code: "SE", name: "Sweden", currency: "SEK", flag: "🇸🇪", symbol: "kr" },
    { code: "CH", name: "Switzerland", currency: "CHF", flag: "🇨🇭", symbol: "Fr" },
    { code: "TW", name: "Taiwan", currency: "TWD", flag: "🇹🇼", symbol: "$" },
    { code: "TJ", name: "Tajikistan", currency: "TJS", flag: "🇹🇯", symbol: "ЅМ" },
    { code: "TZ", name: "Tanzania", currency: "TZS", flag: "🇹🇿", symbol: "Sh" },
    { code: "TH", name: "Thailand", currency: "THB", flag: "🇹🇭", symbol: "฿" },
    { code: "TG", name: "Togo", currency: "XOF", flag: "🇹🇬", symbol: "Fr" },
    { code: "TT", name: "Trinidad and Tobago", currency: "TTD", flag: "🇹🇹", symbol: "$" },
    { code: "TN", name: "Tunisia", currency: "TND", flag: "🇹🇳", symbol: "د.ت" },
    { code: "TR", name: "Turkey", currency: "TRY", flag: "🇹🇷", symbol: "₺" },
    { code: "UG", name: "Uganda", currency: "UGX", flag: "🇺🇬", symbol: "Sh" },
    { code: "UA", name: "Ukraine", currency: "UAH", flag: "🇺🇦", symbol: "₴" },
    { code: "AE", name: "United Arab Emirates", currency: "AED", flag: "🇦🇪", symbol: "د.إ" },
    { code: "GB", name: "United Kingdom", currency: "GBP", flag: "🇬🇧", symbol: "£" },
    { code: "US", name: "United States", currency: "USD", flag: "🇺🇸", symbol: "$" },
    { code: "UY", name: "Uruguay", currency: "UYU", flag: "🇺🇾", symbol: "$" },
    { code: "UZ", name: "Uzbekistan", currency: "UZS", flag: "🇺🇿", symbol: "so'm" },
    { code: "VE", name: "Venezuela", currency: "VES", flag: "🇻🇪", symbol: "Bs." },
    { code: "VN", name: "Vietnam", currency: "VND", flag: "🇻🇳", symbol: "₫" },
    { code: "YE", name: "Yemen", currency: "YER", flag: "🇾🇪", symbol: "﷼" },
    { code: "ZM", name: "Zambia", currency: "ZMW", flag: "🇿🇲", symbol: "ZK" },
    { code: "ZW", name: "Zimbabwe", currency: "ZWL", flag: "🇿🇼", symbol: "$" }
];

// ============ BANKS FOR ALL 180 COUNTRIES ============
const BANKS_BY_COUNTRY = {
    "AF": [{ name: "Afghanistan International Bank", code: "AIB" }, { name: "Azizi Bank", code: "AZB" }, { name: "Bank-e-Millie Afghan", code: "BMA" }, { name: "Ghazanfar Bank", code: "GHB" }],
    "AL": [{ name: "Banka Kombëtare Tregtare", code: "BKT" }, { name: "Raiffeisen Bank Albania", code: "RBA" }, { name: "Intesa Sanpaolo Bank Albania", code: "ISBA" }, { name: "Credins Bank", code: "CRB" }],
    "DZ": [{ name: "Banque Nationale d'Algérie", code: "BNA" }, { name: "Banque Extérieure d'Algérie", code: "BEA" }, { name: "Crédit Populaire d'Algérie", code: "CPA" }, { name: "Société Générale Algérie", code: "SGA" }],
    "AO": [{ name: "Banco Nacional de Angola", code: "BNA" }, { name: "Banco BIC", code: "BIC" }, { name: "Banco de Fomento Angola", code: "BFA" }, { name: "Standard Bank Angola", code: "SBA" }],
    "AR": [{ name: "Banco de la Nación Argentina", code: "BNA" }, { name: "Banco Galicia", code: "GAL" }, { name: "Banco Santander Río", code: "SAN" }, { name: "BBVA Argentina", code: "BBV" }, { name: "Banco Macro", code: "MAC" }],
    "AM": [{ name: "Ameriabank", code: "AME" }, { name: "Ardshinbank", code: "ARD" }, { name: "ACBA Bank", code: "ACB" }, { name: "Converse Bank", code: "CON" }],
    "AU": [{ name: "Commonwealth Bank", code: "CBA" }, { name: "Westpac", code: "WBC" }, { name: "ANZ Bank", code: "ANZ" }, { name: "National Australia Bank", code: "NAB" }, { name: "Macquarie Bank", code: "MAC" }, { name: "Bank of Queensland", code: "BOQ" }],
    "AT": [{ name: "Erste Group Bank", code: "ERS" }, { name: "Raiffeisen Bank International", code: "RBI" }, { name: "UniCredit Bank Austria", code: "UCA" }, { name: "BAWAG", code: "BWG" }],
    "AZ": [{ name: "International Bank of Azerbaijan", code: "IBA" }, { name: "Kapital Bank", code: "KAP" }, { name: "PASHA Bank", code: "PAS" }, { name: "Unibank", code: "UNI" }],
    "BS": [{ name: "Scotiabank Bahamas", code: "SCB" }, { name: "Royal Bank of Canada Bahamas", code: "RBC" }, { name: "FirstCaribbean International Bank", code: "FCI" }, { name: "Commonwealth Bank Bahamas", code: "CBB" }],
    "BH": [{ name: "Ahli United Bank", code: "AUB" }, { name: "Bank of Bahrain and Kuwait", code: "BBK" }, { name: "National Bank of Bahrain", code: "NBB" }, { name: "Arab Banking Corporation", code: "ABC" }],
    "BD": [{ name: "Dutch-Bangla Bank", code: "DBB" }, { name: "BRAC Bank", code: "BRC" }, { name: "Islami Bank Bangladesh", code: "IBB" }, { name: "Sonali Bank", code: "SON" }, { name: "Prime Bank", code: "PRB" }],
    "BB": [{ name: "Republic Bank Barbados", code: "RBB" }, { name: "FirstCaribbean Barbados", code: "FCB" }, { name: "Scotiabank Barbados", code: "SCB" }, { name: "CIBC FirstCaribbean", code: "CFC" }],
    "BY": [{ name: "Belarusbank", code: "BLB" }, { name: "Belagroprombank", code: "BAG" }, { name: "Priorbank", code: "PRI" }, { name: "Alfa-Bank Belarus", code: "ALF" }],
    "BE": [{ name: "BNP Paribas Fortis", code: "BNP" }, { name: "KBC Bank", code: "KBC" }, { name: "ING Belgium", code: "ING" }, { name: "Belfius Bank", code: "BEL" }],
    "BZ": [{ name: "Belize Bank", code: "BLZ" }, { name: "Atlantic Bank", code: "ATL" }, { name: "Scotiabank Belize", code: "SCB" }, { name: "Heritage Bank", code: "HER" }],
    "BJ": [{ name: "Bank of Africa Benin", code: "BOA" }, { name: "Ecobank Benin", code: "ECO" }, { name: "Société Générale Benin", code: "SGB" }, { name: "United Bank for Africa Benin", code: "UBA" }],
    "BT": [{ name: "Bank of Bhutan", code: "BOB" }, { name: "Bhutan National Bank", code: "BNB" }, { name: "Druk PNB Bank", code: "DPN" }, { name: "T-Bank", code: "TBK" }],
    "BO": [{ name: "Banco Nacional de Bolivia", code: "BNB" }, { name: "Banco Mercantil Santa Cruz", code: "BMS" }, { name: "Banco BISA", code: "BIS" }, { name: "Banco de Crédito de Bolivia", code: "BCB" }],
    "BA": [{ name: "Raiffeisen Bank Bosnia", code: "RBB" }, { name: "UniCredit Bank Bosnia", code: "UCB" }, { name: "Intesa Sanpaolo Banka", code: "ISB" }, { name: "Nova Banka", code: "NOV" }],
    "BW": [{ name: "Barclays Bank Botswana", code: "BBB" }, { name: "Standard Chartered Botswana", code: "SCB" }, { name: "First National Bank Botswana", code: "FNB" }, { name: "Bank Gaborone", code: "BGL" }],
    "BR": [{ name: "Banco do Brasil", code: "BDB" }, { name: "Itaú Unibanco", code: "ITA" }, { name: "Bradesco", code: "BRA" }, { name: "Caixa Econômica Federal", code: "CEF" }, { name: "Santander Brasil", code: "SAN" }, { name: "Nubank", code: "NUB" }],
    "BN": [{ name: "Bank Islam Brunei Darussalam", code: "BIBD" }, { name: "Baiduri Bank", code: "BAI" }, { name: "Standard Chartered Brunei", code: "SCB" }],
    "BG": [{ name: "UniCredit Bulbank", code: "UCB" }, { name: "DSK Bank", code: "DSK" }, { name: "First Investment Bank", code: "FIB" }, { name: "United Bulgarian Bank", code: "UBB" }],
    "BF": [{ name: "Bank of Africa Burkina", code: "BOA" }, { name: "Ecobank Burkina", code: "ECO" }, { name: "Société Générale Burkina", code: "SGB" }, { name: "United Bank for Africa Burkina", code: "UBA" }],
    "BI": [{ name: "Bank of the Republic of Burundi", code: "BRB" }, { name: "Ecobank Burundi", code: "ECO" }, { name: "KCB Bank Burundi", code: "KCB" }, { name: "Interbank Burundi", code: "INT" }],
    "CV": [{ name: "Banco Comercial do Atlântico", code: "BCA" }, { name: "Caixa Económica de Cabo Verde", code: "CEC" }, { name: "Banco Interatlântico", code: "BIA" }, { name: "Ecobank Cape Verde", code: "ECO" }],
    "KH": [{ name: "ABA Bank", code: "ABA" }, { name: "ACLEDA Bank", code: "ACL" }, { name: "Canadia Bank", code: "CAN" }, { name: "Sathapana Bank", code: "SAT" }],
    "CM": [{ name: "Afriland First Bank", code: "AFB" }, { name: "Société Générale Cameroun", code: "SGC" }, { name: "Ecobank Cameroun", code: "ECO" }, { name: "UBA Cameroon", code: "UBA" }],
    "CA": [{ name: "RBC Royal Bank", code: "RBC" }, { name: "TD Canada Trust", code: "TDB" }, { name: "Scotiabank", code: "BNS" }, { name: "BMO Bank of Montreal", code: "BMO" }, { name: "CIBC", code: "CM" }, { name: "National Bank of Canada", code: "NBC" }, { name: "Tangerine", code: "TNG" }, { name: "Simplii Financial", code: "SIM" }],
    "CF": [{ name: "Ecobank Centrafrique", code: "ECO" }, { name: "Banque Populaire Maroco-Centrafricaine", code: "BPM" }, { name: "Commercial Bank of Central Africa", code: "CBC" }],
    "TD": [{ name: "Ecobank Tchad", code: "ECO" }, { name: "Société Générale Tchad", code: "SGT" }, { name: "Banque Commerciale du Chari", code: "BCC" }],
    "CL": [{ name: "Banco de Chile", code: "BCH" }, { name: "Banco Santander Chile", code: "SAN" }, { name: "BCI", code: "BCI" }, { name: "BancoEstado", code: "BES" }],
    "CN": [{ name: "Industrial and Commercial Bank of China", code: "ICBC" }, { name: "China Construction Bank", code: "CCB" }, { name: "Agricultural Bank of China", code: "ABC" }, { name: "Bank of China", code: "BOC" }, { name: "China Merchants Bank", code: "CMB" }, { name: "Alipay (Ant Group)", code: "ALI" }, { name: "WeChat Pay", code: "WCP" }],
    "CO": [{ name: "Bancolombia", code: "BCO" }, { name: "Banco de Bogotá", code: "BDB" }, { name: "Davivienda", code: "DAV" }, { name: "BBVA Colombia", code: "BBV" }, { name: "Nequi", code: "NEQ" }],
    "KM": [{ name: "Banque de Développement des Comores", code: "BDC" }, { name: "Banque pour l'Industrie et le Commerce", code: "BIC" }, { name: "Exim Bank Comores", code: "EXB" }],
    "CG": [{ name: "Banque des États de l'Afrique Centrale", code: "BEA" }, { name: "Crédit du Congo", code: "CDC" }, { name: "UBA Congo", code: "UBA" }],
    "CR": [{ name: "Banco Nacional de Costa Rica", code: "BNC" }, { name: "Banco de Costa Rica", code: "BCR" }, { name: "BAC Credomatic", code: "BAC" }, { name: "Banco Popular", code: "BPD" }],
    "CI": [{ name: "Société Générale Côte d'Ivoire", code: "SGI" }, { name: "Bank of Africa Côte d'Ivoire", code: "BOA" }, { name: "Ecobank Côte d'Ivoire", code: "ECO" }, { name: "UBA Côte d'Ivoire", code: "UBA" }],
    "HR": [{ name: "Zagrebačka banka", code: "ZAB" }, { name: "Privredna banka Zagreb", code: "PBZ" }, { name: "Erste Bank Croatia", code: "EBC" }, { name: "OTP Bank Croatia", code: "OTP" }],
    "CU": [{ name: "Banco Nacional de Cuba", code: "BNC" }, { name: "Banco Popular de Ahorro", code: "BPA" }, { name: "Banco de Crédito y Comercio", code: "BCC" }],
    "CY": [{ name: "Bank of Cyprus", code: "BOC" }, { name: "Hellenic Bank", code: "HEL" }, { name: "Eurobank Cyprus", code: "EUC" }, { name: "Alpha Bank Cyprus", code: "ABC" }],
    "CZ": [{ name: "Česká spořitelna", code: "CSS" }, { name: "Komerční banka", code: "KOB" }, { name: "ČSOB", code: "CSO" }, { name: "Air Bank", code: "AIR" }],
    "DK": [{ name: "Danske Bank", code: "DAB" }, { name: "Nordea Bank", code: "NDA" }, { name: "Jyske Bank", code: "JYB" }, { name: "Nykredit", code: "NYK" }],
    "DJ": [{ name: "Banque pour le Commerce et l'Industrie", code: "BCI" }, { name: "Bank of Africa Djibouti", code: "BOA" }],
    "DO": [{ name: "Banco Popular Dominicano", code: "BPD" }, { name: "Banco de Reservas", code: "BDR" }, { name: "Banco BHD León", code: "BHD" }],
    "EC": [{ name: "Banco Pichincha", code: "PIC" }, { name: "Banco del Pacífico", code: "BPA" }, { name: "Banco de Guayaquil", code: "BDG" }, { name: "Produbanco", code: "PRO" }],
    "EG": [{ name: "National Bank of Egypt", code: "NBE" }, { name: "Banque Misr", code: "BM" }, { name: "Commercial International Bank", code: "CIB" }, { name: "QNB Alahli", code: "QNB" }],
    "SV": [{ name: "Banco Agrícola", code: "BAG" }, { name: "Banco Cuscatlán", code: "BCU" }, { name: "Banco Davivienda El Salvador", code: "DAV" }],
    "GQ": [{ name: "Banco Nacional de Guinea Ecuatorial", code: "BNG" }, { name: "CCEI Bank", code: "CCE" }, { name: "Société Générale", code: "SGE" }],
    "ER": [{ name: "Commercial Bank of Eritrea", code: "CBE" }, { name: "Housing and Commerce Bank of Eritrea", code: "HCB" }],
    "EE": [{ name: "Swedbank Estonia", code: "SWE" }, { name: "SEB Bank Estonia", code: "SEB" }, { name: "LHV Bank", code: "LHV" }],
    "SZ": [{ name: "Standard Bank Eswatini", code: "SBE" }, { name: "Nedbank Eswatini", code: "NED" }, { name: "First National Bank Eswatini", code: "FNB" }],
    "ET": [{ name: "Commercial Bank of Ethiopia", code: "CBE" }, { name: "Awash International Bank", code: "AIB" }, { name: "Dashen Bank", code: "DAS" }, { name: "Bank of Abyssinia", code: "BOA" }],
    "FJ": [{ name: "ANZ Fiji", code: "ANZ" }, { name: "Westpac Fiji", code: "WBC" }, { name: "Bank of South Pacific", code: "BSP" }, { name: "Fiji Development Bank", code: "FDB" }],
    "FI": [{ name: "OP Financial Group", code: "OP" }, { name: "Nordea Bank Finland", code: "NDA" }, { name: "Danske Bank Finland", code: "DAB" }],
    "FR": [{ name: "BNP Paribas", code: "BNP" }, { name: "Crédit Agricole", code: "CRA" }, { name: "Société Générale", code: "SGE" }, { name: "BPCE", code: "BPC" }, { name: "Crédit Mutuel", code: "CRM" }],
    "GA": [{ name: "BGFI Bank", code: "BGF" }, { name: "UBA Gabon", code: "UBA" }, { name: "Ecobank Gabon", code: "ECO" }],
    "GM": [{ name: "Standard Chartered Gambia", code: "SCB" }, { name: "GTBank Gambia", code: "GTB" }, { name: "Access Bank Gambia", code: "ACC" }, { name: "Ecobank Gambia", code: "ECO" }],
    "GE": [{ name: "Bank of Georgia", code: "BOG" }, { name: "TBC Bank", code: "TBC" }, { name: "Liberty Bank", code: "LIB" }, { name: "VTB Bank Georgia", code: "VTB" }],
    "DE": [{ name: "Deutsche Bank", code: "DBK" }, { name: "Commerzbank", code: "CBK" }, { name: "DZ Bank", code: "DZB" }, { name: "KfW", code: "KFW" }, { name: "ING Germany", code: "ING" }, { name: "N26", code: "N26" }],
    "GH": [{ name: "GCB Bank", code: "GBC" }, { name: "Ecobank Ghana", code: "ECO" }, { name: "GTBank Ghana", code: "GTB" }, { name: "Access Bank Ghana", code: "ACC" }, { name: "Fidelity Bank Ghana", code: "FBG" }, { name: "UBA Ghana", code: "UBA" }, { name: "Zenith Bank Ghana", code: "ZEN" }, { name: "Stanbic Bank Ghana", code: "STB" }, { name: "Standard Chartered Ghana", code: "SCB" }, { name: "CAL Bank", code: "CAL" }, { name: "ADB Bank", code: "ADB" }, { name: "Bank of Africa Ghana", code: "BOA" }],
    "GR": [{ name: "National Bank of Greece", code: "NBG" }, { name: "Alpha Bank", code: "ALP" }, { name: "Eurobank", code: "EUR" }, { name: "Piraeus Bank", code: "PIR" }],
    "GT": [{ name: "Banco Industrial", code: "BIN" }, { name: "Banco G&T Continental", code: "GTC" }, { name: "Banco de Desarrollo Rural", code: "BDR" }],
    "GN": [{ name: "Ecobank Guinée", code: "ECO" }, { name: "Société Générale Guinée", code: "SGG" }, { name: "UBA Guinée", code: "UBA" }],
    "GW": [{ name: "Banco da África Ocidental", code: "BAO" }, { name: "Ecobank Guiné-Bissau", code: "ECO" }, { name: "UBA Guiné-Bissau", code: "UBA" }],
    "GY": [{ name: "Republic Bank Guyana", code: "RBG" }, { name: "Scotiabank Guyana", code: "SCB" }, { name: "Demerara Bank", code: "DMB" }],
    "HT": [{ name: "Unibank Haiti", code: "UNI" }, { name: "Sogebank", code: "SOG" }, { name: "Banque Nationale de Crédit", code: "BNC" }],
    "HN": [{ name: "Banco Atlántida", code: "BAT" }, { name: "Banco de Occidente", code: "BDO" }, { name: "BAC Honduras", code: "BAC" }],
    "HU": [{ name: "OTP Bank", code: "OTP" }, { name: "K&H Bank", code: "KHB" }, { name: "Erste Bank Hungary", code: "ERH" }, { name: "Raiffeisen Bank Hungary", code: "RBH" }],
    "IS": [{ name: "Íslandsbanki", code: "ISB" }, { name: "Landsbankinn", code: "LAN" }, { name: "Arion Bank", code: "ARI" }],
    "IN": [{ name: "State Bank of India", code: "SBI" }, { name: "HDFC Bank", code: "HDFC" }, { name: "ICICI Bank", code: "ICICI" }, { name: "Axis Bank", code: "AXIS" }, { name: "Kotak Mahindra Bank", code: "KMB" }, { name: "Punjab National Bank", code: "PNB" }, { name: "Bank of Baroda", code: "BOB" }, { name: "Yes Bank", code: "YES" }, { name: "Paytm Payments Bank", code: "PAYT" }, { name: "PhonePe", code: "PHON" }],
    "ID": [{ name: "Bank Mandiri", code: "MDR" }, { name: "Bank Rakyat Indonesia", code: "BRI" }, { name: "Bank Central Asia", code: "BCA" }, { name: "Bank Negara Indonesia", code: "BNI" }, { name: "GoPay", code: "GOP" }, { name: "OVO", code: "OVO" }],
    "IR": [{ name: "Bank Melli Iran", code: "BMI" }, { name: "Bank Saderat Iran", code: "BSI" }, { name: "Bank Pasargad", code: "PAS" }],
    "IQ": [{ name: "Rafidain Bank", code: "RAF" }, { name: "Trade Bank of Iraq", code: "TBI" }, { name: "National Bank of Iraq", code: "NBI" }],
    "IE": [{ name: "Allied Irish Banks", code: "AIB" }, { name: "Bank of Ireland", code: "BOI" }, { name: "Ulster Bank", code: "ULB" }, { name: "Permanent TSB", code: "PTSB" }],
    "IL": [{ name: "Bank Hapoalim", code: "HAP" }, { name: "Bank Leumi", code: "LEU" }, { name: "Israel Discount Bank", code: "IDB" }, { name: "Mizrahi Tefahot Bank", code: "MTB" }],
    "IT": [{ name: "Intesa Sanpaolo", code: "ISP" }, { name: "UniCredit", code: "UCI" }, { name: "Banco BPM", code: "BPM" }, { name: "Monte dei Paschi di Siena", code: "MPS" }],
    "JM": [{ name: "National Commercial Bank Jamaica", code: "NCB" }, { name: "Scotiabank Jamaica", code: "SCB" }, { name: "Sagicor Bank", code: "SAG" }],
    "JP": [{ name: "Mitsubishi UFJ Financial Group", code: "MUFG" }, { name: "Sumitomo Mitsui Banking Corp", code: "SMBC" }, { name: "Mizuho Bank", code: "MIZ" }, { name: "Japan Post Bank", code: "JPB" }, { name: "PayPay Bank", code: "PPB" }],
    "JO": [{ name: "Arab Bank", code: "ARB" }, { name: "Housing Bank for Trade & Finance", code: "HBT" }, { name: "Jordan Islamic Bank", code: "JIB" }],
    "KZ": [{ name: "Halyk Bank", code: "HLK" }, { name: "Kaspi Bank", code: "KSP" }, { name: "ForteBank", code: "FRT" }, { name: "Jusan Bank", code: "JUS" }],
    "KE": [{ name: "KCB Bank", code: "KCB" }, { name: "Equity Bank", code: "EQY" }, { name: "Cooperative Bank", code: "COO" }, { name: "NCBA Bank", code: "NCB" }, { name: "ABSA Bank Kenya", code: "ABS" }, { name: "Stanbic Bank Kenya", code: "STB" }, { name: "Standard Chartered Kenya", code: "SCB" }, { name: "M-Pesa", code: "MPE" }],
    "KW": [{ name: "National Bank of Kuwait", code: "NBK" }, { name: "Kuwait Finance House", code: "KFH" }, { name: "Gulf Bank", code: "GLF" }, { name: "Burgan Bank", code: "BUR" }],
    "KG": [{ name: "Demir Kyrgyz International Bank", code: "DKB" }, { name: "Kyrgyz Investment and Credit Bank", code: "KIC" }, { name: "RSK Bank", code: "RSK" }],
    "LA": [{ name: "Banque pour le Commerce Extérieur Lao", code: "BCE" }, { name: "Phongsavanh Bank", code: "PHO" }, { name: "Lao Development Bank", code: "LDB" }],
    "LV": [{ name: "Swedbank Latvia", code: "SWE" }, { name: "SEB Banka", code: "SEB" }, { name: "Citadele Banka", code: "CIT" }],
    "LB": [{ name: "Bank Audi", code: "AUD" }, { name: "BLOM Bank", code: "BLM" }, { name: "Byblos Bank", code: "BYB" }],
    "LS": [{ name: "Standard Lesotho Bank", code: "SLB" }, { name: "Nedbank Lesotho", code: "NED" }, { name: "First National Bank Lesotho", code: "FNB" }],
    "LR": [{ name: "Ecobank Liberia", code: "ECO" }, { name: "United Bank for Africa Liberia", code: "UBA" }, { name: "GTBank Liberia", code: "GTB" }],
    "LY": [{ name: "Jumhouria Bank", code: "JUM" }, { name: "Sahara Bank", code: "SAH" }, { name: "National Commercial Bank Libya", code: "NCB" }],
    "LT": [{ name: "Swedbank Lithuania", code: "SWE" }, { name: "SEB Bankas", code: "SEB" }, { name: "Revolut Bank", code: "REV" }],
    "LU": [{ name: "BGL BNP Paribas", code: "BGL" }, { name: "Banque Internationale à Luxembourg", code: "BIL" }, { name: "Spuerkeess", code: "SPU" }],
    "MG": [{ name: "Bank of Africa Madagascar", code: "BOA" }, { name: "BNI Madagascar", code: "BNI" }, { name: "Société Générale Madagasikara", code: "SGM" }],
    "MW": [{ name: "National Bank of Malawi", code: "NBM" }, { name: "Standard Bank Malawi", code: "SBM" }, { name: "First Capital Bank", code: "FCB" }],
    "MY": [{ name: "Maybank", code: "MAY" }, { name: "CIMB Bank", code: "CIM" }, { name: "Public Bank", code: "PUB" }, { name: "RHB Bank", code: "RHB" }, { name: "Touch 'n Go eWallet", code: "TNG" }],
    "MV": [{ name: "Bank of Maldives", code: "BML" }, { name: "Maldives Islamic Bank", code: "MIB" }, { name: "State Bank of India Maldives", code: "SBI" }],
    "ML": [{ name: "Bank of Africa Mali", code: "BOA" }, { name: "Ecobank Mali", code: "ECO" }, { name: "UBA Mali", code: "UBA" }],
    "MT": [{ name: "Bank of Valletta", code: "BOV" }, { name: "HSBC Bank Malta", code: "HSBC" }, { name: "BNF Bank", code: "BNF" }],
    "MR": [{ name: "Société Générale Mauritanie", code: "SGM" }, { name: "Banque Mauritanienne pour le Commerce International", code: "BMCI" }],
    "MU": [{ name: "Mauritius Commercial Bank", code: "MCB" }, { name: "SBM Bank Mauritius", code: "SBM" }, { name: "AfrAsia Bank", code: "AFR" }],
    "MX": [{ name: "BBVA México", code: "BBV" }, { name: "Banco Santander México", code: "SAN" }, { name: "Banorte", code: "BNO" }, { name: "Citibanamex", code: "CIT" }],
    "MD": [{ name: "Moldova Agroindbank", code: "MAI" }, { name: "Mobiasbanca", code: "MOB" }, { name: "Victoriabank", code: "VIC" }],
    "MN": [{ name: "Khan Bank", code: "KHA" }, { name: "Golomt Bank", code: "GOL" }, { name: "Trade and Development Bank", code: "TDB" }],
    "MA": [{ name: "Attijariwafa Bank", code: "AWB" }, { name: "Banque Populaire du Maroc", code: "BPM" }, { name: "Bank of Africa Morocco", code: "BOA" }],
    "MZ": [{ name: "Banco Comercial e de Investimentos", code: "BCI" }, { name: "Standard Bank Moçambique", code: "SBM" }, { name: "Millennium bim", code: "BIM" }],
    "MM": [{ name: "KBZ Bank", code: "KBZ" }, { name: "CB Bank", code: "CBB" }, { name: "AYA Bank", code: "AYA" }, { name: "Wave Money", code: "WAV" }],
    "NA": [{ name: "Bank Windhoek", code: "BWH" }, { name: "Standard Bank Namibia", code: "SBN" }, { name: "First National Bank Namibia", code: "FNB" }],
    "NP": [{ name: "Nepal Bank Limited", code: "NBL" }, { name: "Nabil Bank", code: "NAB" }, { name: "Himalayan Bank", code: "HIM" }, { name: "eSewa", code: "ESW" }],
    "NL": [{ name: "ING Group", code: "ING" }, { name: "Rabobank", code: "RAB" }, { name: "ABN AMRO", code: "ABN" }, { name: "Bunq", code: "BUN" }],
    "NZ": [{ name: "ANZ Bank New Zealand", code: "ANZ" }, { name: "ASB Bank", code: "ASB" }, { name: "BNZ", code: "BNZ" }, { name: "Westpac NZ", code: "WBC" }, { name: "Kiwibank", code: "KIW" }],
    "NI": [{ name: "Banco de la Producción", code: "BPR" }, { name: "BAC Nicaragua", code: "BAC" }, { name: "Banco Lafise", code: "LAF" }],
    "NE": [{ name: "Bank of Africa Niger", code: "BOA" }, { name: "Ecobank Niger", code: "ECO" }, { name: "Société Générale Niger", code: "SGN" }],
    "NG": [{ name: "Access Bank", code: "044" }, { name: "Citibank Nigeria", code: "023" }, { name: "Ecobank Nigeria", code: "050" }, { name: "Fidelity Bank", code: "070" }, { name: "First Bank of Nigeria", code: "011" }, { name: "First City Monument Bank (FCMB)", code: "214" }, { name: "Globus Bank", code: "00103" }, { name: "Guaranty Trust Bank (GTBank)", code: "058" }, { name: "Heritage Bank", code: "030" }, { name: "Jaiz Bank", code: "301" }, { name: "Keystone Bank", code: "082" }, { name: "Kuda Bank", code: "50211" }, { name: "Moniepoint", code: "50515" }, { name: "OPay", code: "100004" }, { name: "PalmPay", code: "100033" }, { name: "Polaris Bank", code: "076" }, { name: "Providus Bank", code: "101" }, { name: "Stanbic IBTC Bank", code: "221" }, { name: "Standard Chartered Nigeria", code: "068" }, { name: "Sterling Bank", code: "232" }, { name: "Union Bank of Nigeria", code: "032" }, { name: "United Bank for Africa (UBA)", code: "033" }, { name: "Unity Bank", code: "215" }, { name: "Wema Bank", code: "035" }, { name: "Zenith Bank", code: "057" }],
    "NO": [{ name: "DNB Bank", code: "DNB" }, { name: "Nordea Bank Norge", code: "NDA" }, { name: "SpareBank", code: "SPB" }, { name: "Vipps", code: "VIP" }],
    "OM": [{ name: "Bank Muscat", code: "BKM" }, { name: "National Bank of Oman", code: "NBO" }, { name: "Bank Dhofar", code: "BKD" }],
    "PK": [{ name: "Habib Bank Limited", code: "HBL" }, { name: "United Bank Limited", code: "UBL" }, { name: "MCB Bank", code: "MCB" }, { name: "JazzCash", code: "JC" }, { name: "EasyPaisa", code: "EP" }],
    "PA": [{ name: "Banco General", code: "BGL" }, { name: "Banistmo", code: "BAN" }, { name: "BAC Panama", code: "BAC" }],
    "PG": [{ name: "Bank South Pacific", code: "BSP" }, { name: "Kina Bank", code: "KIN" }, { name: "ANZ Papua New Guinea", code: "ANZ" }],
    "PY": [{ name: "Banco Itaú Paraguay", code: "ITA" }, { name: "Banco Continental", code: "CON" }, { name: "Banco Nacional de Fomento", code: "BNF" }],
    "PE": [{ name: "Banco de Crédito del Perú", code: "BCP" }, { name: "BBVA Perú", code: "BBV" }, { name: "Interbank", code: "INT" }, { name: "Yape", code: "YAP" }],
    "PH": [{ name: "BDO Unibank", code: "BDO" }, { name: "Metrobank", code: "MET" }, { name: "Bank of the Philippine Islands", code: "BPI" }, { name: "GCash", code: "GCS" }, { name: "PayMaya", code: "MAY" }],
    "PL": [{ name: "PKO Bank Polski", code: "PKO" }, { name: "Bank Pekao", code: "PEK" }, { name: "Santander Bank Polska", code: "SAN" }, { name: "mBank", code: "MBK" }, { name: "BLIK", code: "BLK" }],
    "PT": [{ name: "Caixa Geral de Depósitos", code: "CGD" }, { name: "Millennium BCP", code: "BCP" }, { name: "Novo Banco", code: "NOV" }, { name: "Santander Portugal", code: "SAN" }],
    "QA": [{ name: "Qatar National Bank", code: "QNB" }, { name: "Commercial Bank of Qatar", code: "CBQ" }, { name: "Doha Bank", code: "DHB" }, { name: "Qatar Islamic Bank", code: "QIB" }],
    "RO": [{ name: "Banca Transilvania", code: "BTR" }, { name: "BCR", code: "BCR" }, { name: "BRD", code: "BRD" }, { name: "Raiffeisen Bank Romania", code: "RZB" }],
    "RU": [{ name: "Sberbank", code: "SBR" }, { name: "VTB Bank", code: "VTB" }, { name: "Gazprombank", code: "GPB" }, { name: "Alfa-Bank", code: "ALF" }, { name: "Tinkoff Bank", code: "TNK" }],
    "RW": [{ name: "Bank of Kigali", code: "BOK" }, { name: "I&M Bank Rwanda", code: "IMR" }, { name: "KCB Bank Rwanda", code: "KCB" }, { name: "Equity Bank Rwanda", code: "EQY" }],
    "SA": [{ name: "Saudi National Bank", code: "SNB" }, { name: "Al Rajhi Bank", code: "ARB" }, { name: "Riyad Bank", code: "RYB" }, { name: "Samba Bank", code: "SAM" }],
    "SN": [{ name: "Bank of Africa Senegal", code: "BOA" }, { name: "Société Générale Senegal", code: "SGS" }, { name: "Ecobank Senegal", code: "ECO" }, { name: "UBA Senegal", code: "UBA" }],
    "RS": [{ name: "Banca Intesa Serbia", code: "BIS" }, { name: "UniCredit Bank Serbia", code: "UCS" }, { name: "Raiffeisen Bank Serbia", code: "RBS" }],
    "SC": [{ name: "Barclays Bank Seychelles", code: "BAR" }, { name: "Mauritius Commercial Bank Seychelles", code: "MCB" }, { name: "Bank of Ceylon Seychelles", code: "BCS" }],
    "SL": [{ name: "Rokel Commercial Bank", code: "ROK" }, { name: "Sierra Leone Commercial Bank", code: "SLC" }, { name: "Ecobank Sierra Leone", code: "ECO" }, { name: "UBA Sierra Leone", code: "UBA" }],
    "SG": [{ name: "DBS Bank", code: "DBS" }, { name: "OCBC Bank", code: "OCB" }, { name: "United Overseas Bank", code: "UOB" }, { name: "GrabPay", code: "GRB" }],
    "SK": [{ name: "Slovenská sporiteľňa", code: "SLS" }, { name: "VÚB Banka", code: "VUB" }, { name: "Tatra Banka", code: "TAT" }],
    "SI": [{ name: "Nova Ljubljanska Banka", code: "NLB" }, { name: "Nova KBM", code: "NKM" }, { name: "SKB Banka", code: "SKB" }],
    "SO": [{ name: "Premier Bank", code: "PRE" }, { name: "Dahabshiil Bank", code: "DAH" }, { name: "Salaam Somali Bank", code: "SSB" }],
    "ZA": [{ name: "Standard Bank", code: "SBA" }, { name: "First National Bank (FNB)", code: "FNB" }, { name: "ABSA Bank", code: "ABS" }, { name: "Nedbank", code: "NED" }, { name: "Capitec Bank", code: "CAP" }, { name: "TymeBank", code: "TYM" }, { name: "Discovery Bank", code: "DIS" }, { name: "African Bank", code: "AFB" }, { name: "Investec", code: "INV" }],
    "KR": [{ name: "Shinhan Bank", code: "SHB" }, { name: "KB Kookmin Bank", code: "KBB" }, { name: "Woori Bank", code: "WRB" }, { name: "Hana Bank", code: "HAN" }, { name: "KakaoPay", code: "KAK" }],
    "SS": [{ name: "Kenya Commercial Bank South Sudan", code: "KCB" }, { name: "Equity Bank South Sudan", code: "EQY" }, { name: "Stanbic Bank South Sudan", code: "STB" }],
    "ES": [{ name: "Banco Santander", code: "SAN" }, { name: "BBVA", code: "BBV" }, { name: "CaixaBank", code: "CAI" }, { name: "Banco Sabadell", code: "SAB" }],
    "LK": [{ name: "Bank of Ceylon", code: "BOC" }, { name: "People's Bank", code: "PBL" }, { name: "Commercial Bank of Ceylon", code: "COM" }, { name: "Sampath Bank", code: "SAM" }],
    "SD": [{ name: "Bank of Khartoum", code: "BOK" }, { name: "Omdurman National Bank", code: "ONB" }, { name: "Faisal Islamic Bank Sudan", code: "FIB" }],
    "SE": [{ name: "Swedbank", code: "SWE" }, { name: "SEB", code: "SEB" }, { name: "Nordea Sweden", code: "NDA" }, { name: "Handelsbanken", code: "HAN" }, { name: "Swish", code: "SWS" }],
    "CH": [{ name: "UBS", code: "UBS" }, { name: "Credit Suisse", code: "CRS" }, { name: "Raiffeisen Switzerland", code: "RAI" }, { name: "PostFinance", code: "POF" }],
    "TW": [{ name: "Bank of Taiwan", code: "BOT" }, { name: "CTBC Bank", code: "CTC" }, { name: "Taipei Fubon Bank", code: "TFB" }],
    "TJ": [{ name: "Amonatbank", code: "AMO" }, { name: "Orienbank", code: "ORI" }, { name: "First MicroFinance Bank", code: "FMF" }],
    "TZ": [{ name: "CRDB Bank", code: "CRD" }, { name: "NMB Bank Tanzania", code: "NMB" }, { name: "Exim Bank Tanzania", code: "EXI" }, { name: "M-Pesa Tanzania", code: "MPA" }],
    "TH": [{ name: "Bangkok Bank", code: "BBL" }, { name: "Kasikornbank", code: "KBK" }, { name: "Siam Commercial Bank", code: "SCB" }, { name: "Krung Thai Bank", code: "KTB" }, { name: "TrueMoney", code: "TRU" }],
    "TG": [{ name: "Ecobank Togo", code: "ECO" }, { name: "UBA Togo", code: "UBA" }, { name: "Orabank Togo", code: "ORA" }],
    "TT": [{ name: "Republic Bank Trinidad", code: "RBT" }, { name: "Scotiabank Trinidad", code: "SCB" }, { name: "First Citizens Bank", code: "FCB" }],
    "TN": [{ name: "Banque Internationale Arabe de Tunisie", code: "BIAT" }, { name: "Société Tunisienne de Banque", code: "STB" }, { name: "Amen Bank", code: "AMN" }],
    "TR": [{ name: "Ziraat Bankası", code: "ZIR" }, { name: "İş Bankası", code: "ISB" }, { name: "Garanti BBVA", code: "GAR" }, { name: "Akbank", code: "AKB" }, { name: "Yapı Kredi", code: "YKB" }],
    "UG": [{ name: "Stanbic Bank Uganda", code: "STB" }, { name: "Standard Chartered Uganda", code: "SCB" }, { name: "Centenary Bank", code: "CEN" }, { name: "MTN Mobile Money", code: "MTN" }, { name: "Airtel Money", code: "AIR" }],
    "UA": [{ name: "PrivatBank", code: "PRV" }, { name: "Oschadbank", code: "OSC" }, { name: "Ukreximbank", code: "UEX" }, { name: "Monobank", code: "MON" }],
    "AE": [{ name: "Emirates NBD", code: "ENB" }, { name: "First Abu Dhabi Bank", code: "FAB" }, { name: "Abu Dhabi Commercial Bank", code: "ADC" }, { name: "Dubai Islamic Bank", code: "DIB" }, { name: "Mashreq Bank", code: "MAS" }, { name: "RAK Bank", code: "RAK" }],
    "GB": [{ name: "HSBC UK", code: "HSBC" }, { name: "Barclays", code: "BAR" }, { name: "Lloyds Bank", code: "LLO" }, { name: "NatWest", code: "NWB" }, { name: "Santander UK", code: "SAN" }, { name: "Nationwide", code: "NWD" }, { name: "Monzo", code: "MON" }, { name: "Revolut", code: "REV" }, { name: "Starling Bank", code: "STR" }],
    "US": [{ name: "Bank of America", code: "BOA" }, { name: "Chase Bank", code: "CHS" }, { name: "Wells Fargo", code: "WFC" }, { name: "Citibank", code: "CIT" }, { name: "US Bank", code: "USB" }, { name: "PNC Bank", code: "PNC" }, { name: "TD Bank", code: "TDB" }, { name: "Capital One", code: "CPO" }, { name: "Goldman Sachs", code: "GSC" }, { name: "Morgan Stanley", code: "MGS" }, { name: "Cash App", code: "CSH" }, { name: "Venmo", code: "VEN" }, { name: "PayPal", code: "PPL" }, { name: "Zelle", code: "ZEL" }],
    "UY": [{ name: "Banco República", code: "BRO" }, { name: "Banco Santander Uruguay", code: "SAN" }, { name: "Banco Itaú Uruguay", code: "ITA" }],
    "UZ": [{ name: "National Bank of Uzbekistan", code: "NBU" }, { name: "Asaka Bank", code: "ASA" }, { name: "Ipoteka Bank", code: "IPO" }],
    "VE": [{ name: "Banco de Venezuela", code: "BDV" }, { name: "Banesco", code: "BAN" }, { name: "Banco Mercantil Venezuela", code: "BMV" }],
    "VN": [{ name: "Vietcombank", code: "VCB" }, { name: "BIDV", code: "BID" }, { name: "VietinBank", code: "VTB" }, { name: "Techcombank", code: "TCB" }, { name: "MoMo", code: "MOM" }, { name: "ZaloPay", code: "ZLP" }],
    "YE": [{ name: "National Bank of Yemen", code: "NBY" }, { name: "Cooperative & Agricultural Credit Bank", code: "CAC" }],
    "ZM": [{ name: "Zanaco", code: "ZAN" }, { name: "Standard Chartered Zambia", code: "SCB" }, { name: "First National Bank Zambia", code: "FNB" }, { name: "Atlas Mara Zambia", code: "AMZ" }],
    "ZW": [{ name: "CBZ Bank", code: "CBZ" }, { name: "Stanbic Bank Zimbabwe", code: "STB" }, { name: "Standard Chartered Zimbabwe", code: "SCB" }, { name: "EcoCash", code: "ECO" }]
};

// ============ EXCHANGE RATES ============
const EXCHANGE_RATES = {
    "AFN": 72, "ALL": 95, "DZD": 134, "AOA": 830, "ARS": 850, "AMD": 400, "AUD": 1.53, "AZN": 1.70,
    "BSD": 1, "BHD": 0.38, "BDT": 110, "BBD": 2, "BYN": 3.2, "BZD": 2, "XOF": 600, "BTN": 83,
    "BOB": 6.9, "BAM": 1.83, "BWP": 13.5, "BRL": 5.05, "BND": 1.34, "BGN": 1.83, "BIF": 2850,
    "CVE": 100, "KHR": 4100, "XAF": 600, "CAD": 1.36, "CLP": 880, "CNY": 7.24, "COP": 3900,
    "KMF": 450, "CRC": 530, "CUP": 24, "CZK": 22.5, "DKK": 6.8, "DJF": 178, "DOP": 57,
    "EGP": 48, "ERN": 15, "ETB": 56, "EUR": 0.92, "FJD": 2.2, "GMD": 65, "GEL": 2.65,
    "GHS": 12.5, "GTQ": 7.8, "GNF": 8600, "GYD": 210, "HTG": 130, "HNL": 24.5, "HUF": 360,
    "ISK": 138, "INR": 83, "IDR": 15700, "IRR": 42000, "IQD": 1310, "ILS": 3.7, "JMD": 155,
    "JPY": 149, "JOD": 0.71, "KZT": 450, "KES": 145, "KWD": 0.31, "KGS": 89, "LAK": 21000,
    "LBP": 89500, "LSL": 18.5, "LRD": 190, "LYD": 4.8, "MGA": 4500, "MWK": 1700, "MYR": 4.7,
    "MVR": 15.4, "MRU": 40, "MUR": 44, "MXN": 17.2, "MDL": 17.8, "MNT": 3400, "MAD": 10,
    "MZN": 64, "MMK": 2100, "NAD": 18.5, "NPR": 133, "NZD": 1.63, "NIO": 36.5, "NGN": 1550,
    "NOK": 10.5, "OMR": 0.38, "PKR": 278, "PAB": 1, "PGK": 3.8, "PYG": 7300, "PEN": 3.7,
    "PHP": 56, "PLN": 3.95, "QAR": 3.64, "RON": 4.6, "RUB": 90, "RWF": 1280, "SAR": 3.75,
    "RSD": 108, "SCR": 14, "SLL": 22000, "SGD": 1.34, "SOS": 570, "ZAR": 18.5, "KRW": 1320,
    "SSP": 600, "LKR": 320, "SDG": 600, "SEK": 10.3, "CHF": 0.88, "TWD": 31.5, "TJS": 11,
    "TZS": 2500, "THB": 35.5, "TTD": 6.8, "TND": 3.1, "TRY": 31, "UGX": 3800, "UAH": 38,
    "AED": 3.67, "GBP": 0.79, "USD": 1, "UYU": 39, "UZS": 12500, "VES": 36, "VND": 24600,
    "YER": 250, "ZMW": 26, "ZWL": 322
};

function getCountryByCode(code) { return COUNTRIES.find(function(c) { return c.code === code; }) || { code:"US", name:"United States", currency:"USD", flag:"🇺🇸", symbol:"$" }; }
function getBanksForCountry(code) { return BANKS_BY_COUNTRY[code] || [{ name: "International Bank", code: "INTL" }]; }
function getExchangeRate(currency) { return EXCHANGE_RATES[currency] || 1; }
function formatLocalCurrency(usdAmount) { return (usdAmount * (APP_STATE.exchangeRate || 1)).toFixed(2); }

console.log('✅ Countries.js loaded: ' + COUNTRIES.length + ' countries, banks for ' + Object.keys(BANKS_BY_COUNTRY).length + ' countries');